kind = "mobile"
previewPath = "/"
title = "Maddar Employee"
version = "1.0.0"
id = "artifacts/maddar-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22536

[services.development]
run = "pnpm --filter @workspace/maddar-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/maddar-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/maddar-mobile", "run", "serve" ]

[services.env]
PORT = "22536"
BASE_PATH = "/"
